version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "./start.sh"] 
    volumes:
      - .:/app
    ports:
      - "8012:8000"
    env_file:
      - .env
    container_name: my-password-container-app 