# Generated by Django 5.1.4 on 2025-01-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='category',
            field=models.CharField(choices=[('business', 'BUSSINESS'), ('finance', 'FINANCE'), ('gym', 'GYM')], null=True),
        ),
    ]
