# Generated by Django 5.1.4 on 2024-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_passwordentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
