# Generated by Django 5.1.4 on 2025-01-05 03:43

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_passwordentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='category',
            field=models.CharField(choices=[('youtube', 'YOUTUBE'), ('gmail', 'GMAIL'), ('other', 'OTHER')], null=True),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='encrypted_password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
